name: Regenerate Readme

on:
  push:
    branches: [master]

jobs:
  generate-readme:
    name: Generate a fresh README with the latest documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://dev.to/davidwessman/error-when-converting-pdf-to-image-on-github-actions-2m5m
      - name: Allow ImageMagick PDF access
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml

      - name: Run readme generator
        run: bash .github/workflows/generate-readme.sh

      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: "Update README.md with latest thumbnails"
          rebase: "true"
