name: Regenerate Readme

on: push

jobs:
    generate-readme:
        name: Generate a fresh README with the latest documents
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Run readme generator
              run: bash ./github/workflows/generate-readme.sh
