name: Regenerate Readme

on:
  workflow_dispatch:
  
  push:
    branches: [master]

jobs:
  generate-readme:
    name: Generate a fresh README with the latest documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # https://dev.to/davidwessman/error-when-converting-pdf-to-image-on-github-actions-2m5m
      - name: Allow ImageMagick PDF access
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml

      - name: Run readme generator
        run: bash .github/workflows/generate-readme.sh

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Automatically update README with latest thumbnails" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
